# SPDX-License-Identifier: GPL-2.0-only
# A removed package leaves conffiles behind; keep ordinary DKMS builds usable.
if [[ -r /usr/share/psycachy-nvidia-support/override.sh ]]; then
    . /usr/share/psycachy-nvidia-support/override.sh
fi
